### ISSUE TITLE
A Bug With Responsive Version

### ISSUE THREAD

**Issue by krypton225** [catherineisonline/personal-portfolio#2]
You created awesome work in your portfolio website. I liked it and liked its design. Well done!

But there is small bug with responsive version. The scrolling in x-axis showed when the site be opened in mobile phone in example. This is a small bug you can fix it easily.

I like you to fix that ASAP!

Good luck, Catherine!

**Comment by catherineisonline** [comment]
Thanks for trying to help. What do you mean by "The scrolling in x-axis showed", do you mean that the scroll bar on right is visible and that's a bug?

**Comment by krypton225** [comment]
Yes. When you open the inspect in chrome or another browser and try to show the website in mobile mode, you will see the scroll bar in x-axis which you can scroll the web page right and left.

This makes the page not appear in the correct way, or in a more correct sense, it does not appear in a beautiful way, as you know that the appearance of the scroll bar in x-axis on the page is not something that is desirable for anyone :)

That helps you to show the site better.
